config/routes.rb
ExemploMigration::Application.routes.draw do
  resources :cidades

  resources :estados

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
  belongs_to :estado
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :cidades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  # GET /cidades
  # GET /cidades.xml
  def index
    @cidades = Cidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cidades }
    end
  end

  # GET /cidades/1
  # GET /cidades/1.xml
  def show
    @cidade = Cidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cidade }
    end
  end

  # GET /cidades/new
  # GET /cidades/new.xml
  def new
    @cidade = Cidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cidade }
    end
  end

  # GET /cidades/1/edit
  def edit
    @cidade = Cidade.find(params[:id])
  end

  # POST /cidades
  # POST /cidades.xml
  def create
    @cidade = Cidade.new(params[:cidade])

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to(@cidade, :notice => 'Cidade was successfully created.') }
        format.xml  { render :xml => @cidade, :status => :created, :location => @cidade }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cidade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cidades/1
  # PUT /cidades/1.xml
  def update
    @cidade = Cidade.find(params[:id])

    respond_to do |format|
      if @cidade.update_attributes(params[:cidade])
        format.html { redirect_to(@cidade, :notice => 'Cidade was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cidade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.xml
  def destroy
    @cidade = Cidade.find(params[:id])
    @cidade.destroy

    respond_to do |format|
      format.html { redirect_to(cidades_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  # GET /estados
  # GET /estados.xml
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.xml
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.xml
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.xml
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to(@estado, :notice => 'Estado was successfully created.') }
        format.xml  { render :xml => @estado, :status => :created, :location => @estado }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.xml
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to(@estado, :notice => 'Estado was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @estado.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.xml
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to(estados_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/cidades/_form.html.erb
<%= form_for(@cidade) do |f| %>
  <% if @cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% @cidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing cidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<h1>Listing cidades</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cidades.each do |cidade| %>
  <tr>
    <td><%= cidade.nome %></td>
    <td><%= cidade.estado.nome %></td>
    <td><%= link_to 'Show', cidade %></td>
    <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
    <td><%= link_to 'Destroy', cidade, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cidade', new_cidade_path %>

app/views/cidades/new.html.erb
<h1>New cidade</h1>

<%= render 'form' %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cidade.nome %>
</p>

<p>
  <b>Estado:</b>
  <%= @cidade.estado %>
</p>


<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>

app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sigla %><br />
    <%= f.text_field :sigla %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<h1>Listing estados</h1>

<table>
  <tr>
    <th>Sigla</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estados.each do |estado| %>
  <tr>
    <td><%= estado.sigla %></td>
    <td><%= estado.nome %></td>
    <td><%= link_to 'Show', estado %></td>
    <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
    <td><%= link_to 'Destroy', estado, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New estado</h1>

<%= render 'form' %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sigla:</b>
  <%= @estado.sigla %>
</p>

<p>
  <b>Nome:</b>
  <%= @estado.nome %>
</p>


<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExemploMigration</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>